# Generated by Django 6.0.7 on 2026-07-31 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='projected_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
