# Generated by Django 6.0.7 on 2026-08-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobtask_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtask',
            name='type',
            field=models.CharField(choices=[('document_send', 'Document Send'), ('image_extract', 'Image Extract'), ('voice_transcribe', 'Voice Transcribe')], max_length=20),
        ),
    ]
