"""
Django settings for accountant_backend project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import dotenv
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

dotenv.load_dotenv(BASE_DIR / ".env")

_INSECURE_DEFAULT_SECRET_KEY = "django-insecure-q4hnf6=zmafgasd!o&-_jnhqtk5s$f*lng9$^4s3&d1v)5olmk"

# SECURITY WARNING: don't run with debug turned on in production! Defaults to
# False (safe-by-default) — DJANGO_DEBUG must be explicitly set to "True" to
# enable it, rather than the previous default that silently ran with DEBUG on
# unless someone remembered to turn it off for a real deployment.
DEBUG = os.environ.get("DJANGO_DEBUG", "False") == "True"

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "")
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = _INSECURE_DEFAULT_SECRET_KEY
    else:
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY must be set via environment/.env when DJANGO_DEBUG is not "
            "'True' — refusing to start a production server on the insecure default key."
        )
elif SECRET_KEY == _INSECURE_DEFAULT_SECRET_KEY and not DEBUG:
    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY is set to the known insecure default — generate and set a real "
        "secret key before running with DJANGO_DEBUG=False."
    )

_allowed_hosts_env = os.environ.get("DJANGO_ALLOWED_HOSTS", "")
if _allowed_hosts_env:
    ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_env.split(",") if h.strip()]
elif DEBUG:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1"]
else:
    raise ImproperlyConfigured(
        "DJANGO_ALLOWED_HOSTS must be set (comma-separated real domain(s)/IP(s)) when "
        "DJANGO_DEBUG is not 'True'."
    )

# Behind a reverse proxy (nginx, a PaaS load balancer, etc.) terminating TLS,
# Django needs this to correctly detect that the original request was HTTPS —
# without it, SECURE_SSL_REDIRECT below would redirect-loop forever.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

if not DEBUG:
    # HTTPS-only hardening — only enabled in production so local HTTP dev
    # against localhost keeps working without a cert.
    SECURE_SSL_REDIRECT = os.environ.get("DJANGO_SECURE_SSL_REDIRECT", "True") == "True"
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.environ.get("DJANGO_SECURE_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'apps.accounts',
    'apps.customers',
    'apps.sales',
    'apps.jobs',
    'apps.documents',
    'apps.billing',
    'apps.chat',
    'apps.image_info_extractor',
    'apps.notifications',
    'apps.whatsapp',
    'apps.agent',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTH_USER_MODEL = 'accounts.User'

# The Flutter app is a native HTTP client, not a browser, so CORS doesn't
# apply to it — this setting only matters if/when a browser-based admin
# panel or web client is added. DJANGO_CORS_ALLOWED_ORIGINS lets that be
# configured explicitly in production instead of ever defaulting to "*".
_cors_origins_env = os.environ.get("DJANGO_CORS_ALLOWED_ORIGINS", "")
if _cors_origins_env:
    CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_origins_env.split(",") if o.strip()]
else:
    CORS_ALLOW_ALL_ORIGINS = DEBUG

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'EXCEPTION_HANDLER': 'apps.accounts.exceptions.custom_exception_handler',
    # Request-rate abuse protection — separate from apps.billing's monthly
    # per-feature usage caps (that's business-plan quota; this is raw
    # request-flood/brute-force protection at the HTTP layer). 'auth' is a
    # tighter scope applied explicitly to login/register/Google-auth via
    # apps.accounts.throttling.AuthRateThrottle; 'anon'/'user' are DRF's
    # built-in defaults, applied to every other view automatically.
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': os.environ.get('DJANGO_THROTTLE_ANON_RATE', '30/minute'),
        'user': os.environ.get('DJANGO_THROTTLE_USER_RATE', '120/minute'),
        'auth': os.environ.get('DJANGO_THROTTLE_AUTH_RATE', '10/minute'),
        # PDF generation queues real work (render + disk write) on the same
        # worker the AI jobs use, so it gets its own tighter ceiling.
        'documents': os.environ.get('DJANGO_THROTTLE_DOCUMENTS_RATE', '20/minute'),
    },
}

# DRF throttling counts requests via Django's cache framework — no CACHES
# setting here means it falls back to Django's default per-process
# LocMemCache. That's fine for a single-worker deployment (the SQLite path
# this app runs on for now), but if you ever run multiple gunicorn/uwsgi
# worker processes, each process gets its own counter and throttling stops
# being accurate across them — switch to a shared cache (e.g. Redis via
# django-redis) at that point.

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
}

GOOGLE_OAUTH_CLIENT_ID = os.environ.get("GOOGLE_OAUTH_CLIENT_ID", "")
FASTAPI_INTERNAL_KEY = os.environ.get("FASTAPI_INTERNAL_KEY", "")
FASTAPI_BASE_URL = os.environ.get("FASTAPI_BASE_URL", "http://localhost:8001")

# Shared filesystem folder that FastAPI writes generated PDFs into and Django serves back to the
# phone — both services point at the same absolute path via PDF_STORAGE_DIR/MEDIA_ROOT env vars.
MEDIA_URL = "/media/"
MEDIA_ROOT = Path(os.environ.get("MEDIA_ROOT", BASE_DIR.parent / "shared_media"))

def _collect_keys(var_name, max_n=10):
    """Reads `var_name` plus `var_name_1`..`var_name_{max_n}` from the
    environment and returns whichever are actually set, in that order —
    used for free-tier key rotation (apps.chat.groq_client /
    apps.image_info_extractor.gemini_client): when one key's quota is
    exhausted, the client tries the next one automatically rather than
    failing the request. Duplicates are dropped. An empty list means
    "not configured" (same meaning the single-key settings used to have)."""
    keys = []
    single = os.environ.get(var_name, "").strip()
    if single:
        keys.append(single)
    for i in range(1, max_n + 1):
        value = os.environ.get(f"{var_name}_{i}", "").strip()
        if value and value not in keys:
            keys.append(value)
    return keys


# GROQ_API_KEY (bare) still works alone for a single-key setup; add
# GROQ_API_KEY_1, _2, ... up to _20 for automatic rotation across multiple
# free-tier accounts once one starts hitting rate limits. The cap is a plain
# function argument (max_n) — raise it here alone if you ever need more than
# 20, nothing else in the rotation code has a hardcoded count.
GROQ_API_KEYS = _collect_keys("GROQ_API_KEY", max_n=20)
GROQ_MODEL_FAST = os.environ.get("GROQ_MODEL_FAST", "llama-3.1-8b-instant")
GROQ_MODEL_REASONING = os.environ.get("GROQ_MODEL_REASONING", "llama-3.3-70b-versatile")

# Vision extraction: Gemini is called directly from Django's job worker for now (see
# ai_automation_layer.md Section 3) — an empty GEMINI_API_KEYS list means the worker fails
# that job cleanly with a NOT_CONFIGURED error until at least one key is added. Same
# GEMINI_API_KEY_1.._20 rotation convention as Groq above.
GEMINI_API_KEYS = _collect_keys("GEMINI_API_KEY", max_n=20)
# Handwritten shopkeeper bills are the hard case, and flash-lite misreads them often
# enough to matter. Note the *Pro* models are not a drop-in upgrade here: on the free
# tier they return 429 RESOURCE_EXHAUSTED, which would fail every extraction. Stay on a
# flash-tier model unless the key is on a paid plan.
GEMINI_MODEL = os.environ.get("GEMINI_MODEL", "gemini-3.6-flash")

# Tried in order when GEMINI_MODEL fails. The failure this exists for is
# `503 UNAVAILABLE - "This model is currently experiencing high demand"`, which
# took out receipt extraction entirely: it is the model being busy, so retrying
# on another API key changes nothing. Keep these flash-tier for the same reason
# GEMINI_MODEL is (Pro 429s on a free-tier key).
#
# Reading a handwritten bill is the accuracy-critical path in this product — a
# misread rate becomes wrong money on someone's ledger — so vision NEVER falls
# back to a lite model. `gemini-2.5-flash` is deliberately absent: Google has
# retired it for newer API keys (404 "no longer available to new users"), so a
# chain containing it breaks the moment a fresh key is added to the rotation.
GEMINI_FALLBACK_MODELS = [
    m.strip()
    for m in os.environ.get("GEMINI_FALLBACK_MODELS", "gemini-flash-latest").split(",")
    if m.strip()
]

# Transliteration only (Urdu script <-> Roman Urdu). Not accuracy-critical in
# the money sense — the worst case is an awkward-sounding word — so this may use
# a lighter, cheaper model than vision. Kept separate precisely so tuning chat
# costs can never quietly downgrade receipt reading.
GEMINI_TEXT_MODEL = os.environ.get("GEMINI_TEXT_MODEL", "gemini-3.6-flash")
GEMINI_TEXT_FALLBACK_MODELS = [
    m.strip()
    for m in os.environ.get(
        "GEMINI_TEXT_FALLBACK_MODELS", "gemini-flash-latest,gemini-3.1-flash-lite"
    ).split(",")
    if m.strip()
]

# Chat's fast/planner tier (see apps.chat.services.select_model_tier) — moved
# off Groq's llama-3.1-8b-instant onto Google's Gemma via the Generative
# Language API (the same canonical Google client
# apps.image_info_extractor.gemini_client uses — see
# apps.integrations.google_genai_client).
#
# FAST_GEMINI_API_KEYS is its own key pool, separate from GEMINI_API_KEYS
# (OCR) and QUALITY_GEMINI_API_KEYS (chat's reasoning tier, below) — these
# three features used to compete for one shared pool's free-tier daily
# quota; splitting them means each gets its own independent allowance.
# Falls back to GEMINI_API_KEYS if no dedicated keys are configured, so an
# existing single-pool .env keeps working unchanged.
FAST_GEMINI_API_KEYS = _collect_keys("FAST_GEMINI_API_KEY", max_n=20) or GEMINI_API_KEYS
GOOGLE_FAST_MODEL = os.environ.get("GOOGLE_FAST_MODEL", "gemma-4-31b-it")
GOOGLE_FAST_FALLBACK_MODELS = [
    m.strip()
    for m in os.environ.get("GOOGLE_FAST_FALLBACK_MODELS", "").split(",")
    if m.strip()
]

# Chat's reasoning/quality tier (see apps.chat.services._call_model and
# _write_final_reply) — moved off Groq's llama-3.3-70b-versatile onto
# Gemini (apps.chat.google_client.call_gemini_reasoning). This is the
# highest-volume chat traffic (every bill/edit/document-intent message,
# plus the entire Roman Urdu/Urdu response-writer pass), so it gets its own
# key pool, never shared with the fast tier or OCR — see FAST_GEMINI_API_KEYS
# above for why that separation matters. Falls back to GEMINI_API_KEYS if
# unset.
QUALITY_GEMINI_API_KEYS = _collect_keys("QUALITY_GEMINI_API_KEY", max_n=20) or GEMINI_API_KEYS
GOOGLE_QUALITY_MODEL = os.environ.get("GOOGLE_QUALITY_MODEL", "gemini-3.6-flash")
GOOGLE_QUALITY_FALLBACK_MODELS = [
    m.strip()
    for m in os.environ.get("GOOGLE_QUALITY_FALLBACK_MODELS", "gemini-flash-latest").split(",")
    if m.strip()
]

# Voice-note transcription (apps.voice_transcriber): a recorded chat message is
# uploaded as audio and transcribed here before it ever reaches the chat
# planner — see apps.voice_transcriber.google_client. Kept on the same
# flash-tier constraint as GEMINI_TEXT_MODEL above (this key's Pro models 429),
# and deliberately its own setting rather than reusing GEMINI_TEXT_MODEL: audio
# transcription cost/accuracy tuning must not silently move the transliteration
# path too.
#
# Its own key pool too, separate from GEMINI_API_KEYS (OCR) — every voice
# note used to draw from OCR's quota; a business recording several voice
# messages could exhaust the same pool a photographed bill needs. Falls
# back to GEMINI_API_KEYS if unset.
AUDIO_GEMINI_API_KEYS = _collect_keys("AUDIO_GEMINI_API_KEY", max_n=20) or GEMINI_API_KEYS
GEMINI_AUDIO_MODEL = os.environ.get("GEMINI_AUDIO_MODEL", "gemini-3.1-flash-lite")
GEMINI_AUDIO_FALLBACK_MODELS = [
    m.strip()
    for m in os.environ.get("GEMINI_AUDIO_FALLBACK_MODELS", "gemini-flash-latest").split(",")
    if m.strip()
]

# Runs the job worker as a thread inside the web process instead of as a
# separate `manage.py runworker`. For free hosting tiers that have no
# always-on background process (Render free, PythonAnywhere free) — without it,
# photo extraction and WhatsApp sends queue forever with no error. Leave it off
# wherever a real worker process can be run; that stays the better option.
RUN_WORKER_IN_PROCESS = os.environ.get("RUN_WORKER_IN_PROCESS", "False") == "True"
WORKER_POLL_INTERVAL = float(os.environ.get("WORKER_POLL_INTERVAL", "2.0"))

WHATSAPP_GATEWAY_BASE_URL = os.environ.get("WHATSAPP_GATEWAY_BASE_URL", "http://localhost:3000/api/v1")
WHATSAPP_GATEWAY_JWT_SECRET = os.environ.get("WHATSAPP_GATEWAY_JWT_SECRET", "")

ROOT_URLCONF = 'accountant_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'accountant_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# SQLite (file-based, single-writer) is fine for local dev and a small early
# launch, but not for real concurrent production traffic long-term. Set
# DATABASE_URL (e.g. postgres://user:pass@host:5432/dbname) to switch to
# Postgres — nothing else in the app depends on the database engine, this is
# a drop-in swap when you're ready to migrate.
# Requires `psycopg[binary]` and `dj-database-url` (see requirements.txt).
#
# Running production on SQLite deliberately, for now (e.g. launching solo
# before a Postgres migration): set DJANGO_ALLOW_SQLITE_IN_PRODUCTION=True to
# acknowledge this and skip the guard below. This is an explicit opt-in, not
# a default, so it stays visible in your env config as a reminder it's
# temporary rather than something that silently slipped through.

_database_url = os.environ.get("DATABASE_URL", "")
_allow_sqlite_in_prod = os.environ.get("DJANGO_ALLOW_SQLITE_IN_PRODUCTION", "False") == "True"
if _database_url:
    import dj_database_url

    DATABASES = {
        'default': dj_database_url.parse(_database_url, conn_max_age=600, ssl_require=not DEBUG)
    }
elif not DEBUG and not _allow_sqlite_in_prod:
    raise ImproperlyConfigured(
        "DATABASE_URL must be set (e.g. postgres://user:pass@host:5432/dbname) when "
        "DJANGO_DEBUG is not 'True'. If you're intentionally running production on SQLite "
        "for now, set DJANGO_ALLOW_SQLITE_IN_PRODUCTION=True instead."
    )
else:
    # NOTE: with DEBUG=False and no DATABASE_URL, this is the
    # DJANGO_ALLOW_SQLITE_IN_PRODUCTION opt-in path — same file-based engine
    # as local dev, just pointed at whatever BASE_DIR resolves to on the
    # production host. Back this file up; SQLite has no built-in replication.
    #
    # A busy timeout matters a lot once this is a real multi-request
    # production server instead of a single dev process: without it,
    # concurrent writes (two sales saved at the same moment, etc.) commonly
    # fail immediately with "database is locked" instead of briefly queuing.
    # WAL journal mode (which allows concurrent readers alongside a writer)
    # is enabled separately via the `connection_created` signal below —
    # SQLite's Django backend has no OPTIONS key for arbitrary PRAGMAs
    # (`init_command` is a MySQL-only option; passing it here would just be
    # silently ignored/error, not actually set WAL mode).
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            'OPTIONS': {
                'timeout': 20,
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# The business timezone. Every "today", every date printed on a document, and
# every statement/report boundary resolves against this — not the server's
# clock. Timestamps are still stored in UTC (USE_TZ below); this only decides
# how they are interpreted as business dates.
#
# It was UTC, which put the day boundary at 05:00 Pakistan time: a sale entered
# at 1am appeared on the previous day's report and printed yesterday's date on
# the customer's invoice.
TIME_ZONE = os.environ.get("DJANGO_TIME_ZONE", "Asia/Karachi")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
