# Generated by Django 6.0.7 on 2026-07-29 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_pkr', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_custom', models.BooleanField(default=False)),
                ('billing_period', models.CharField(default='monthly', max_length=20)),
                ('chat_history_limit', models.PositiveIntegerField(default=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_manual_override', models.BooleanField(default=False)),
                ('chat_history_limit_override', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='accounts.business')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan')),
            ],
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_key', models.CharField(choices=[('ai_chat', 'AI Chat'), ('voice_reply', 'Voice Reply'), ('image_extraction', 'Image Extraction'), ('whatsapp_send', 'WhatsApp Send')], max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('monthly_cap', models.PositiveIntegerField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='billing.plan')),
            ],
            options={
                'unique_together': {('plan', 'feature_key')},
            },
        ),
        migrations.CreateModel(
            name='UsageCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_key', models.CharField(choices=[('ai_chat', 'AI Chat'), ('voice_reply', 'Voice Reply'), ('image_extraction', 'Image Extraction'), ('whatsapp_send', 'WhatsApp Send')], max_length=50)),
                ('period_start', models.DateField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_counters', to='accounts.business')),
            ],
            options={
                'unique_together': {('business', 'feature_key', 'period_start')},
            },
        ),
    ]
