# Generated by Django 6.0.7 on 2026-07-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='draft_action',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
