# Generated by Django 6.0.7 on 2026-07-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatsyncstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='draft_document',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
