# Generated by Django 6.0.7 on 2026-08-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chatmessage_pending_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='draft_customer',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
