# Generated by Django 6.0.7 on 2026-08-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_chatmessage_draft_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='report_view',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
