# Generated by Django 6.0.7 on 2026-08-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_chatmessage_draft_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='audio_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
