# Generated by Django 6.0.7 on 2026-07-29 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('jobs', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateddocument',
            name='job_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to='jobs.jobtask'),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='related_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.activityentry'),
        ),
    ]
