# Generated by Django 6.0.7 on 2026-07-30 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('customers', '0001_initial'),
        ('documents', '0002_initial'),
        ('jobs', '0002_alter_jobtask_type'),
        ('sales', '0003_alter_entrychangelog_action_alter_pendingundo_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('invoice', 'Invoice'), ('statement', 'Statement'), ('receipt', 'Receipt'), ('report', 'Report')], max_length=20)),
                ('requested_format', models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF')], max_length=10)),
                ('delivered_format', models.CharField(blank=True, choices=[('image', 'Image'), ('pdf', 'PDF')], max_length=10, null=True)),
                ('to_phone', models.CharField(max_length=50)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=64, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('byte_size', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_deliveries', to='accounts.business')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_deliveries', to='customers.customer')),
                ('job_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_deliveries', to='jobs.jobtask')),
                ('related_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_deliveries', to='sales.activityentry')),
            ],
            options={
                'verbose_name_plural': 'document deliveries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='GeneratedDocument',
        ),
        migrations.AddIndex(
            model_name='documentdelivery',
            index=models.Index(fields=['business', '-created_at'], name='documents_d_busines_3de287_idx'),
        ),
        migrations.AddIndex(
            model_name='documentdelivery',
            index=models.Index(fields=['business', 'status'], name='documents_d_busines_33b376_idx'),
        ),
    ]
