# Generated by Django 6.0.7 on 2026-07-31 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documentdelivery_delete_generateddocument_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentdelivery',
            old_name='sent_at',
            new_name='accepted_at',
        ),
        migrations.AlterField(
            model_name='documentdelivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Queued'), ('sending', 'Sending'), ('accepted', 'Accepted by WhatsApp'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
