# Generated by Django 6.0.7 on 2026-07-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_draft_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_error_fallback',
            field=models.BooleanField(default=False),
        ),
    ]
