# Generated by Django 6.0.7 on 2026-07-31 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('chat', '0004_chatmessage_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_cleared_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sync_state', to='accounts.business')),
            ],
        ),
    ]
