# Generated by Django 6.0.7 on 2026-08-02 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chatmessage_draft_document'),
        ('documents', '0005_sent_status_to_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='pending_delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='documents.documentdelivery'),
        ),
    ]
