# Generated by Django 6.0.7 on 2026-08-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_chatmessage_report_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='draft_payment',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
