# Generated by Django 6.0.7 on 2026-08-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_business_address_business_email_business_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_type',
            field=models.CharField(blank=True, choices=[('HARDWARE', 'Hardware Store'), ('PAINT_STORE', 'Paint Store'), ('ELECTRICAL', 'Electrical Store'), ('GARMENTS_ACCESSORIES', 'Garments Accessories'), ('GARMENTS', 'Garments'), ('FABRIC', 'Fabric Store'), ('TEXTILE', 'Textile'), ('RICE_GRAIN', 'Rice / Grain Dealer'), ('FLOUR_MILL', 'Flour Mill'), ('GENERAL_STORE', 'General Store'), ('GROCERY', 'Grocery'), ('RESTAURANT', 'Restaurant'), ('HOTEL', 'Hotel'), ('BAKERY', 'Bakery'), ('FAST_FOOD', 'Fast Food'), ('TEA_SHOP', 'Tea Shop'), ('MEDICAL_STORE', 'Medical Store'), ('PHARMACY', 'Pharmacy'), ('BIKE_WORKSHOP', 'Bike Workshop'), ('BIKE_PARTS', 'Bike Parts'), ('CAR_WORKSHOP', 'Car Workshop'), ('TYRE_SHOP', 'Tyre Shop'), ('CONSTRUCTION', 'Construction Material'), ('STEEL', 'Steel'), ('CEMENT', 'Cement'), ('SANITARY', 'Sanitary'), ('TILES', 'Tiles'), ('PLASTIC', 'Plastic'), ('WHOLESALE', 'Wholesale'), ('RETAIL', 'Retail'), ('MOBILE_SHOP', 'Mobile Shop'), ('COMPUTER_SHOP', 'Computer Shop'), ('ELECTRONICS', 'Electronics'), ('FURNITURE', 'Furniture'), ('PRINTING_PRESS', 'Printing Press'), ('STATIONERY', 'Stationery'), ('JEWELRY', 'Jewelry'), ('COSMETICS', 'Cosmetics'), ('BEAUTY_SALON', 'Beauty Salon'), ('TAILOR', 'Tailor'), ('LAUNDRY', 'Laundry'), ('MILK_SHOP', 'Milk Shop'), ('FRUIT_SHOP', 'Fruit Shop'), ('VEGETABLE_SHOP', 'Vegetable Shop'), ('POULTRY', 'Poultry'), ('OTHER', 'Other')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='business',
            name='special_instructions',
            field=models.TextField(blank=True, default=''),
        ),
    ]
