# Generated by Django 6.0.7 on 2026-07-30 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('invoice_sent', 'Invoice Sent'), ('payment_received', 'Payment Received'), ('whatsapp_disconnected', 'WhatsApp Disconnected'), ('pending_payment_reminder', 'Pending Payment Reminder'), ('daily_summary', 'Daily Summary')], max_length=30)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.business')),
            ],
            options={
                'ordering': ['-timestamp', '-id'],
            },
        ),
    ]
