# Generated by Django 6.0.7 on 2026-07-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('invoice_sent', 'Invoice Sent'), ('document_failed', 'Document Send Failed'), ('payment_received', 'Payment Received'), ('whatsapp_disconnected', 'WhatsApp Disconnected'), ('pending_payment_reminder', 'Pending Payment Reminder'), ('daily_summary', 'Daily Summary')], max_length=30),
        ),
    ]
