# Generated by Django 6.0.7 on 2026-08-02 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('chat', '0006_chatmessage_draft_document'),
        ('documents', '0005_sent_status_to_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_request', models.JSONField(blank=True, default=dict)),
                ('plan', models.JSONField(blank=True, default=list)),
                ('current_step', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('awaiting_clarification', 'Awaiting clarification'), ('awaiting_authorization', 'Awaiting authorization'), ('executing', 'Executing'), ('awaiting_verification', 'Awaiting verification'), ('done', 'Done'), ('failed', 'Failed')], default='planning', max_length=32)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_goals', to='accounts.business')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_goals', to='chat.conversation')),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_goals', to='documents.documentdelivery')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_goals', to='chat.chatmessage')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['conversation', 'status'], name='agent_agent_convers_957358_idx'), models.Index(fields=['business', 'status'], name='agent_agent_busines_bd6e58_idx')],
            },
        ),
    ]
