# Generated by Django 6.0.7 on 2026-07-30 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('edit', 'Edit'), ('transfer', 'Transfer')], max_length=10)),
                ('old_values', models.JSONField()),
                ('new_values', models.JSONField()),
                ('source', models.CharField(default='ai_chat', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_change_logs', to='accounts.business')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PendingUndo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('edit', 'Edit'), ('transfer', 'Transfer')], max_length=10)),
                ('snapshot', models.JSONField()),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_undos', to='accounts.business')),
            ],
        ),
    ]
