# Generated by Django 6.0.7 on 2026-07-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_entrychangelog_pendingundo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrychangelog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('edit', 'Edit'), ('transfer', 'Transfer')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pendingundo',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('edit', 'Edit'), ('transfer', 'Transfer')], max_length=10),
        ),
    ]
