# Generated by Django 6.0.7 on 2026-07-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtask',
            name='type',
            field=models.CharField(choices=[('document_send', 'Document Send'), ('image_extract', 'Image Extract')], max_length=20),
        ),
    ]
