# Generated by Django 6.0.7 on 2026-08-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_jobtask_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtask',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
